apiVersion: apps/v1
kind: Deployment
metadata:
  name: gregflix-client
  namespace: gregflix
  labels:
    app.kubernetes.io/name: gregflix-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gregflix-client
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gregflix-client
    spec:
      containers:
        - name: gregflix-client
          image: gregflix-client:test
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "3000"
            - name: HOSTNAME
              value: 0.0.0.0
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
